import type { Agency, Job, Rep, Thread } from "./types";

const initials = (name: string) =>
  `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent(name)}&backgroundType=gradientLinear&fontFamily=Inter&fontWeight=600`;

export const reps: Rep[] = [
  {
    id: "r_amara",
    name: "Amara Okafor",
    headline: "Closer for AI infra & dev-tools — $20k+ ACVs",
    avatar: initials("Amara Okafor"),
    location: "Lisbon, PT",
    yearsExperience: 6,
    industries: ["DevTools", "AI Infra", "Cybersecurity"],
    motions: ["Closing", "Full-cycle"],
    ticketRange: "$15k–$120k ACV",
    rate: "$6k/mo + 12%",
    available: "Now",
    score: { overall: 92, discovery: 94, objectionHandling: 91, closing: 95, talkRatio: 88 },
    verified: true,
    stats: { closedDeals: 138, avgDealSize: "$32k", quotaAttainmentPct: 138 },
    bio: "Six years selling technical products to engineering buyers. I run tight discovery, push for next steps, and have a soft spot for late-stage objection handling.",
  },
  {
    id: "r_jules",
    name: "Jules Reyes",
    headline: "AI agency SDR — books 18 qualified meetings / month",
    avatar: initials("Jules Reyes"),
    location: "Austin, TX",
    yearsExperience: 2,
    industries: ["AI Services", "Marketing", "SaaS"],
    motions: ["Outbound", "SDR"],
    ticketRange: "$3k–$25k MRR",
    rate: "$3k/mo + 8%",
    available: "2 weeks",
    score: { overall: 84, discovery: 87, objectionHandling: 80, closing: 78, talkRatio: 91 },
    verified: true,
    stats: { closedDeals: 41, avgDealSize: "$11k", quotaAttainmentPct: 121 },
    bio: "I love the top of funnel. Multi-channel outbound with personalized loom intros, and I share my call recordings without ego.",
  },
  {
    id: "r_dani",
    name: "Dani Volkov",
    headline: "First-year closer — verified 88, hungry, coachable",
    avatar: initials("Dani Volkov"),
    location: "Berlin, DE",
    yearsExperience: 1,
    industries: ["AI Agencies", "Creator Tools"],
    motions: ["Closing", "SDR"],
    ticketRange: "$2k–$15k MRR",
    rate: "$2.5k/mo + 15%",
    available: "Now",
    score: { overall: 88, discovery: 86, objectionHandling: 89, closing: 90, talkRatio: 86 },
    verified: true,
    stats: { closedDeals: 22, avgDealSize: "$8k", quotaAttainmentPct: 112 },
    bio: "Came up through a high-volume call center, then leveled up with coaching. Built for AI agency offers between $3k–$10k/mo.",
  },
  {
    id: "r_sana",
    name: "Sana Iyer",
    headline: "Enterprise closer — six-figure ACVs in fintech & AI",
    avatar: initials("Sana Iyer"),
    location: "Singapore",
    yearsExperience: 9,
    industries: ["Fintech", "AI Platforms", "Enterprise SaaS"],
    motions: ["Closing", "Full-cycle"],
    ticketRange: "$80k–$500k ACV",
    rate: "$9k/mo + 10%",
    available: "1 month",
    score: { overall: 95, discovery: 96, objectionHandling: 94, closing: 96, talkRatio: 91 },
    verified: true,
    stats: { closedDeals: 211, avgDealSize: "$127k", quotaAttainmentPct: 142 },
    bio: "Multi-threaded enterprise deals are my sweet spot. I write the mutual action plan on call one and never let a deal go dark.",
  },
  {
    id: "r_marco",
    name: "Marco Halloran",
    headline: "Done-for-you agency closer — outbound + close",
    avatar: initials("Marco Halloran"),
    location: "Dublin, IE",
    yearsExperience: 4,
    industries: ["AI Agencies", "B2B Services"],
    motions: ["Outbound", "Closing", "Full-cycle"],
    ticketRange: "$5k–$40k MRR",
    rate: "$4k/mo + 12%",
    available: "Now",
    score: { overall: 89, discovery: 90, objectionHandling: 88, closing: 91, talkRatio: 84 },
    verified: true,
    stats: { closedDeals: 96, avgDealSize: "$19k", quotaAttainmentPct: 129 },
    bio: "I built two AI agencies to seven figures before going freelance. I close what I'd buy.",
  },
  {
    id: "r_priya",
    name: "Priya Anand",
    headline: "Demo-to-close specialist — 36% win rate on inbounds",
    avatar: initials("Priya Anand"),
    location: "Bangalore, IN",
    yearsExperience: 3,
    industries: ["AI SaaS", "RevOps", "MarTech"],
    motions: ["Closing", "Full-cycle"],
    ticketRange: "$8k–$60k ACV",
    rate: "$3.5k/mo + 14%",
    available: "Now",
    score: { overall: 87, discovery: 89, objectionHandling: 85, closing: 88, talkRatio: 89 },
    verified: true,
    stats: { closedDeals: 64, avgDealSize: "$22k", quotaAttainmentPct: 117 },
    bio: "I treat every demo like a discovery call. Numbers do the closing.",
  },
];

export const agencies: Agency[] = [
  {
    id: "a_loophole",
    name: "Loophole AI",
    logo: initials("Loophole"),
    offer: "Done-for-you AI voice agents for home services — $7k/mo retainers.",
    ticket: "$7k MRR",
    closeRate: "31%",
    vertical: "AI / Home Services",
    hq: "Miami, FL",
    team: 14,
    fundingStage: "Bootstrapped, profitable",
    verified: true,
  },
  {
    id: "a_signal",
    name: "Signal Studio",
    logo: initials("Signal"),
    offer: "AI growth ops for B2B SaaS Series A–B. $12k/mo strategic + execution.",
    ticket: "$12k MRR",
    closeRate: "24%",
    vertical: "AI / B2B SaaS",
    hq: "London, UK",
    team: 22,
    fundingStage: "Seed",
    verified: true,
  },
  {
    id: "a_northwall",
    name: "Northwall.ai",
    logo: initials("Northwall"),
    offer: "Custom AI workflows for legal & finance ops. $30k–$120k engagements.",
    ticket: "$80k project",
    closeRate: "19%",
    vertical: "AI / Professional Services",
    hq: "New York, NY",
    team: 38,
    fundingStage: "Series A",
    verified: true,
  },
  {
    id: "a_kindling",
    name: "Kindling",
    logo: initials("Kindling"),
    offer: "AI-generated short-form for creators & brands. $4k/mo subscriptions.",
    ticket: "$4k MRR",
    closeRate: "27%",
    vertical: "AI / Creator Economy",
    hq: "Los Angeles, CA",
    team: 9,
    verified: true,
  },
];

export const jobs: Job[] = [
  {
    id: "j_1",
    agencyId: "a_loophole",
    title: "Closer — AI voice agents for home services",
    type: "Closer",
    comp: "$60k base + uncapped",
    commission: "12% MRR for 12 months",
    remote: "Remote",
    region: "Americas",
    postedDays: 2,
    tags: ["Inbound demos", "Warm leads", "$7k MRR"],
    description:
      "Close warm inbound demos from our SDR team. Average deal $7k/mo, sales cycle 9 days, 31% win rate.",
  },
  {
    id: "j_2",
    agencyId: "a_signal",
    title: "Founding AE — B2B SaaS AI growth ops",
    type: "Founding AE",
    comp: "$80k base + equity + comm",
    commission: "10% Y1 ACV",
    remote: "Hybrid",
    region: "EU / UK",
    postedDays: 5,
    tags: ["Full-cycle", "Founder-led", "$12k MRR"],
    description:
      "Own the full cycle alongside the founders. You'll inherit a pipeline of 30 warm Series A CMOs.",
  },
  {
    id: "j_3",
    agencyId: "a_northwall",
    title: "Enterprise AE — Custom AI for legal & finance",
    type: "Full-cycle AE",
    comp: "$110k base + uncapped",
    commission: "8% project value",
    remote: "Hybrid",
    region: "US East Coast",
    postedDays: 9,
    tags: ["6-figure deals", "Enterprise", "Multi-thread"],
    description:
      "Multi-threaded enterprise sales to GCs, CFOs, and Ops leaders. 6–14 week cycles, $30k–$120k engagements.",
  },
  {
    id: "j_4",
    agencyId: "a_kindling",
    title: "SDR — Outbound to creators & brand teams",
    type: "SDR",
    comp: "$45k base + comm",
    commission: "$200 per booked qualified meeting",
    remote: "Remote",
    region: "Global",
    postedDays: 1,
    tags: ["Outbound", "Loom-first", "Creator economy"],
    description:
      "Multi-channel outbound: email, LinkedIn, and personalized Loom. Target 22 qualified meetings/month.",
  },
  {
    id: "j_5",
    agencyId: "a_loophole",
    title: "SDR — Inbound qualification, AI home services",
    type: "SDR",
    comp: "$50k base + comm",
    commission: "$300 per SQL handed off",
    remote: "Remote",
    region: "Americas",
    postedDays: 12,
    tags: ["Inbound", "Qualification", "Warm leads"],
    description:
      "Qualify 60+ warm inbounds per week. Hand off SQLs to our closer team.",
  },
];

export const threads: Thread[] = [
  {
    id: "t_1",
    category: "Wins",
    title: "Closed my first $7k/mo agency retainer 4 weeks after joining Closer",
    author: "Dani V.",
    authorAvatar: initials("Dani V"),
    replies: 47,
    likes: 312,
    postedAgo: "2h",
    preview:
      "Wanted to share the script tweak that finally got me off the 'we'll think about it' loop. The reframe is...",
  },
  {
    id: "t_2",
    category: "Objections",
    title: "Best response to 'send me the deck and I'll review with my team'",
    author: "Marco H.",
    authorAvatar: initials("Marco H"),
    replies: 28,
    likes: 184,
    postedAgo: "6h",
    preview:
      "Stop sending the deck. Here's the 3-line response I use to get them to invite the decision maker to call two.",
  },
  {
    id: "t_3",
    category: "Scripts",
    title: "Cold opener that books 1 in 4 meetings for AI voice agents",
    author: "Jules R.",
    authorAvatar: initials("Jules R"),
    replies: 64,
    likes: 421,
    postedAgo: "1d",
    preview:
      "Pattern interrupt + outcome + permission. Verbatim script below, plus the loom variant.",
  },
  {
    id: "t_4",
    category: "Tools",
    title: "Closer score 92+ — here's my actual prep checklist before every demo",
    author: "Amara O.",
    authorAvatar: initials("Amara O"),
    replies: 19,
    likes: 256,
    postedAgo: "1d",
    preview:
      "It's not the CRM. It's the 10 minutes before the call. Sharing the full checklist plus the LinkedIn template.",
  },
  {
    id: "t_5",
    category: "Hiring",
    title: "Hiring a closer for an AI agency — what should I actually pay?",
    author: "Northwall founder",
    authorAvatar: initials("Northwall"),
    replies: 35,
    likes: 142,
    postedAgo: "3d",
    preview:
      "Market check: base, commission, and on-target earnings for $7k–$15k MRR AI offers in 2026.",
  },
  {
    id: "t_6",
    category: "Wins",
    title: "Verified 95 → six offers in a week",
    author: "Sana I.",
    authorAvatar: initials("Sana I"),
    replies: 22,
    likes: 198,
    postedAgo: "5d",
    preview:
      "The badge changed everything. Hiring managers stopped asking for my resume and started asking when I could start.",
  },
];

export const sampleScore = reps[3].score;
